# Form implementation generated from reading ui file 'assignment05.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_assignment05(object):
    def setupUi(self, assignment05):
        assignment05.setObjectName("assignment05")
        assignment05.resize(473, 393)
        self.centralwidget = QtWidgets.QWidget(parent=assignment05)
        self.centralwidget.setObjectName("centralwidget")
        self.nameLabelOne = QtWidgets.QLabel(parent=self.centralwidget)
        self.nameLabelOne.setGeometry(QtCore.QRect(110, 70, 71, 16))
        self.nameLabelOne.setObjectName("nameLabel")
        self.numberOneLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.numberOneLabel.setGeometry(QtCore.QRect(110, 100, 71, 16))
        self.numberOneLabel.setObjectName("numberOneLabel")
        self.numberTwoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.numberTwoLabel.setGeometry(QtCore.QRect(110, 130, 71, 16))
        self.numberTwoLabel.setObjectName("numberTwoLabel")
        self.numberThreeLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.numberThreeLabel.setGeometry(QtCore.QRect(110, 160, 71, 16))
        self.numberThreeLabel.setObjectName("numberThreeLabel")
        self.calculateButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calculateButton.setGeometry(QtCore.QRect(70, 190, 113, 32))
        self.calculateButton.setObjectName("calculateButton")
        self.exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(220, 190, 113, 32))
        self.exitButton.setObjectName("exitButton")
        self.nameDisplay = QtWidgets.QLabel(parent=self.centralwidget)
        self.nameDisplay.setGeometry(QtCore.QRect(100, 230, 91, 16))
        self.nameDisplay.setText("")
        self.nameDisplay.setObjectName("nameDisplay")
        self.nameLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nameLine.setGeometry(QtCore.QRect(180, 70, 113, 21))
        self.nameLine.setObjectName("nameLine")
        self.numberLineOne = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.numberLineOne.setGeometry(QtCore.QRect(180, 100, 113, 21))
        self.numberLineOne.setObjectName("numberLineOne")
        self.numberLineTwo = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.numberLineTwo.setGeometry(QtCore.QRect(180, 130, 113, 21))
        self.numberLineTwo.setObjectName("numberLineTwo")
        self.numberLineThree = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.numberLineThree.setGeometry(QtCore.QRect(180, 160, 113, 21))
        self.numberLineThree.setObjectName("numberLineThree")
        self.nameLabelTwo = QtWidgets.QLabel(parent=self.centralwidget)
        self.nameLabelTwo.setGeometry(QtCore.QRect(100, 240, 171, 16))
        self.nameLabelTwo.setObjectName("nameLabel")
        self.sumLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.sumLabel.setGeometry(QtCore.QRect(100, 260, 171, 16))
        self.sumLabel.setObjectName("productLabel")
        self.productLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.productLabel.setGeometry(QtCore.QRect(100, 280, 171, 16))
        self.productLabel.setObjectName("productLabel")
        self.averageLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.averageLabel.setGeometry(QtCore.QRect(100, 300, 171, 16))
        self.averageLabel.setObjectName("averageLabel")
        assignment05.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=assignment05)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 473, 21))
        self.menubar.setObjectName("menubar")
        assignment05.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=assignment05)
        self.statusbar.setObjectName("statusbar")
        assignment05.setStatusBar(self.statusbar)

        self.retranslateUi(assignment05)
        QtCore.QMetaObject.connectSlotsByName(assignment05)

    def retranslateUi(self, assignment05):
        _translate = QtCore.QCoreApplication.translate
        assignment05.setWindowTitle(_translate("assignment05", "MainWindow"))
        self.nameLabelOne.setText(_translate("assignment05", "<html><head/><body><p><span style=\" font-weight:600;\">Name:</span></p></body></html>"))
        self.numberOneLabel.setText(_translate("assignment05", "<html><head/><body><p><span style=\" font-weight:600;\">Number 1:</span></p></body></html>"))
        self.numberTwoLabel.setText(_translate("assignment05", "<html><head/><body><p><span style=\" font-weight:600;\">Number 2:</span></p></body></html>"))
        self.numberThreeLabel.setText(_translate("assignment05", "<html><head/><body><p><span style=\" font-weight:600;\">Number 3:</span></p></body></html>"))
        self.calculateButton.setText(_translate("assignment05", "Calculate"))
        self.exitButton.setText(_translate("assignment05", "Exit"))
        self.averageLabel.setText(_translate("assignment05", "Average: "))
        self.nameLabelTwo.setText(_translate("assignment05", "Name: "))
        self.productLabel.setText(_translate("assignment05", "Product: "))
        self.sumLabel.setText(_translate("assignment05", "Sum: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    assignment05 = QtWidgets.QMainWindow()
    ui = Ui_assignment05()
    ui.setupUi(assignment05)
    assignment05.show()
    sys.exit(app.exec())
